### ISSUE TITLE
Rubric checklist - Server Side

### ISSUE THREAD

**Issue by jlavar1** [JustinTorrance/notez#10]
- [ ] 4 - All requirements from 3 met, and all endpoints are tested (both happy and sad paths).
- [ ] 3 - Application hosts all required endpoints, and an effort has been made to test them.
- [ ] 2 - Application hosts all required endpoints, but none are tested.
- [ ] 1 - Application does not host all required endpoints.
