### ISSUE TITLE
Rubric Checklist - Specification Adherence

### ISSUE THREAD

**Issue by jlavar1** [JustinTorrance/notez#6]
- [ ] 4 - All requirements from 3 are met. The application completes all requirements above and implements one or more of the extensions. And the evaluator has no recommendations for design changes.
- [ ] 3 - The application completes all requirements above without error. Evaluator has minimal recommendations for design changes.
- [ ] 2 - The application is in a usable state, but is missing part of one or more of the features outlined above. Evaluator has multiple recommendations for design changes.
- [ ] 1 - The application is missing multiple features outlined above. Developer did minimal to no CSS for this project.
