### ISSUE TITLE
Rubric Checklist - Redux architecture

### ISSUE THREAD

**Issue by jlavar1** [JustinTorrance/notez#8]
- [ ] 4 - All requirements from 3 met, and no duplication of data exists in the store. Data in the store remains flat (not nested).
- [ ] 3 - Appropriate components are wrapped in connected Redux container components. The Redux store contains all necessary application data. All state changes are handled through Redux actions and reducers.
- [ ] 2 - At least one component is not connected with Redux appropriately. Application state is mutated by more than just Redux. The Redux store is missing application data that it should be handling.
- [ ] 1 - Application state is mostly outside the control of Redux. Application did not make use of Redux actions and reducers to mutate state. Components do not demonstrate a clear understanding of stateful vs. statelessness.
