### ISSUE TITLE
Rubric checklist - routing

### ISSUE THREAD

**Issue by jlavar1** [JustinTorrance/notez#9]
- [ ] 4 - All requirements from 3 met, and always chooses the correct component for rendering, as well as the correct Route API. The application should account for undefined routes.
- [ ] 3 - Application uses React Router to display appropriate components based on URL.
- [ ] 2 - Application uses React Router, but does not display the appropriate components upon navigating.
- [ ] 1 - Application uses React Router, but does not render/use all routes.
